### ISSUE TITLE
Issue in installing Clean Package with Umbraco version 11.2

### ISSUE THREAD

**Issue by myrashed** [prjseal/Clean-Starter-Kit-for-Umbraco-v9#14]
I'm facing issue when running 
dotnet add package Clean --version 2.1.6

from CMD and from Package manger in VS.NET

![image](https://user-images.githubusercontent.com/858670/224496287-3464dc0d-3d2f-40f2-be83-3aa326b2747c.png)

**Comment by OwainJ** [comment]
I've just tested this with the latest version of Umbraco 11 (v11.5.0) and the latest version of the Clean starter kit (3.1.4), and it installed correctly.

![image](https://github.com/prjseal/Clean-Starter-Kit-for-Umbraco-v9/assets/17008780/280a0acf-070f-4155-ab91-f455a563cbe0)

**Comment by myrashed** [comment]
Thank you @OwainJ  yes it's working now, after a couple of tries looks like some nuget apackes was failed to be downsloaded.

**Comment by myrashed** [comment]
Consider it's closed
