### ISSUE TITLE
Blog & Contact pages fail on Linux

### ISSUE THREAD

**Issue by craigs100** [prjseal/Clean-Starter-Kit-for-Umbraco-v9#18]
Umb 12.1.1, Clean Starter Kit 3.0.2

Installed on Linux Mint with SQLite. Site runs fine except clicking Blog or Contact in the main navigation results in errors:-

```InvalidOperationException: The view 'Components/Pagination/Default' was not found.```
```InvalidOperationException: The view 'Components/Contact/Default' was not found.```

This is because the views have been named /default.cshtml and not /Default.cshtml as they should be.  Renaming the files corrects the errors.

**Comment by prjseal** [comment]
Thanks for testing it for me @craigs100 
I’ll fix it next week

**Comment by prjseal** [comment]
Hi @craigs100 
I have released a new version, can you let me know if that works for you now please?

Thanks

Paul

**Comment by craigs100** [comment]
Hi @prjseal,

Thanks, just tested it and all appears to be working now :)

**Comment by prjseal** [comment]
Thanks @craigs100 I will close this issue now
